/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 11.3.0-1ubuntu1~22.04 -fPIC -O3) */

module clk_div(clk, n_rst, lim, hzX, counter);
  wire [22:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  input clk;
  wire clk;
  output [22:0] counter;
  wire [22:0] counter;
  output hzX;
  wire hzX;
  input [22:0] lim;
  wire [22:0] lim;
  input n_rst;
  wire n_rst;
  sky130_fd_sc_hd__xnor2_1 _069_ (
    .A(lim[10]),
    .B(counter[10]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__xor2_1 _070_ (
    .A(lim[7]),
    .B(counter[7]),
    .X(_041_)
  );
  sky130_fd_sc_hd__xor2_1 _071_ (
    .A(lim[14]),
    .B(counter[14]),
    .X(_042_)
  );
  sky130_fd_sc_hd__xor2_1 _072_ (
    .A(lim[1]),
    .B(counter[1]),
    .X(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _073_ (
    .A(lim[5]),
    .B(counter[5]),
    .X(_044_)
  );
  sky130_fd_sc_hd__xnor2_1 _074_ (
    .A(lim[3]),
    .B(counter[3]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xnor2_1 _075_ (
    .A(lim[22]),
    .B(counter[22]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__xnor2_1 _076_ (
    .A(counter[0]),
    .B(lim[0]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xor2_1 _077_ (
    .A(lim[4]),
    .B(counter[4]),
    .X(_048_)
  );
  sky130_fd_sc_hd__xnor2_1 _078_ (
    .A(lim[18]),
    .B(counter[18]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xor2_1 _079_ (
    .A(lim[12]),
    .B(counter[12]),
    .X(_050_)
  );
  sky130_fd_sc_hd__xor2_1 _080_ (
    .A(lim[21]),
    .B(counter[21]),
    .X(_051_)
  );
  sky130_fd_sc_hd__xor2_1 _081_ (
    .A(lim[9]),
    .B(counter[9]),
    .X(_052_)
  );
  sky130_fd_sc_hd__xnor2_1 _082_ (
    .A(lim[15]),
    .B(counter[15]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__xor2_1 _083_ (
    .A(lim[11]),
    .B(counter[11]),
    .X(_054_)
  );
  sky130_fd_sc_hd__xnor2_1 _084_ (
    .A(lim[19]),
    .B(counter[19]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__xnor2_1 _085_ (
    .A(lim[13]),
    .B(counter[13]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__xor2_1 _086_ (
    .A(lim[16]),
    .B(counter[16]),
    .X(_057_)
  );
  sky130_fd_sc_hd__xor2_1 _087_ (
    .A(lim[2]),
    .B(counter[2]),
    .X(_058_)
  );
  sky130_fd_sc_hd__xor2_1 _088_ (
    .A(lim[6]),
    .B(counter[6]),
    .X(_059_)
  );
  sky130_fd_sc_hd__nand4_1 _089_ (
    .A(_040_),
    .B(_045_),
    .C(_047_),
    .D(_049_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand4_1 _090_ (
    .A(_046_),
    .B(_053_),
    .C(_055_),
    .D(_056_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xor2_1 _091_ (
    .A(lim[17]),
    .B(counter[17]),
    .X(_062_)
  );
  sky130_fd_sc_hd__nor4_1 _092_ (
    .A(_044_),
    .B(_054_),
    .C(_059_),
    .D(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor4_1 _093_ (
    .A(_041_),
    .B(_043_),
    .C(_052_),
    .D(_057_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__xor2_1 _094_ (
    .A(lim[20]),
    .B(counter[20]),
    .X(_065_)
  );
  sky130_fd_sc_hd__nor4_1 _095_ (
    .A(_042_),
    .B(_048_),
    .C(_058_),
    .D(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xor2_1 _096_ (
    .A(lim[8]),
    .B(counter[8]),
    .X(_067_)
  );
  sky130_fd_sc_hd__nor3_1 _097_ (
    .A(_050_),
    .B(_051_),
    .C(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand4_1 _098_ (
    .A(_063_),
    .B(_064_),
    .C(_066_),
    .D(_068_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor3_1 _099_ (
    .A(_060_),
    .B(_061_),
    .C(_002_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _100_ (
    .A(counter[0]),
    .B(_001_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__xnor2_1 _101_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _102_ (
    .A(_001_),
    .B(_003_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _103_ (
    .A1(counter[1]),
    .A2(counter[0]),
    .B1(counter[2]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__and3_1 _104_ (
    .A(counter[1]),
    .B(counter[2]),
    .C(counter[0]),
    .X(_005_)
  );
  sky130_fd_sc_hd__nor3_1 _105_ (
    .A(_001_),
    .B(_004_),
    .C(_005_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__nor2_1 _106_ (
    .A(counter[3]),
    .B(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__and4_1 _107_ (
    .A(counter[1]),
    .B(counter[2]),
    .C(counter[3]),
    .D(counter[0]),
    .X(_007_)
  );
  sky130_fd_sc_hd__nor3_1 _108_ (
    .A(_001_),
    .B(_006_),
    .C(_007_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__nor2_1 _109_ (
    .A(counter[4]),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__and2_0 _110_ (
    .A(counter[4]),
    .B(_007_),
    .X(_009_)
  );
  sky130_fd_sc_hd__nor3_1 _111_ (
    .A(_001_),
    .B(_008_),
    .C(_009_),
    .Y(_000_[4])
  );
  sky130_fd_sc_hd__xnor2_1 _112_ (
    .A(counter[5]),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _113_ (
    .A(_001_),
    .B(_010_),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__a21oi_1 _114_ (
    .A1(counter[5]),
    .A2(_009_),
    .B1(counter[6]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__and4_1 _115_ (
    .A(counter[4]),
    .B(counter[5]),
    .C(counter[6]),
    .D(_007_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nor3_1 _116_ (
    .A(_001_),
    .B(_011_),
    .C(_012_),
    .Y(_000_[6])
  );
  sky130_fd_sc_hd__and2_0 _117_ (
    .A(counter[7]),
    .B(_012_),
    .X(_013_)
  );
  sky130_fd_sc_hd__nor2_1 _118_ (
    .A(counter[7]),
    .B(_012_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor3_1 _119_ (
    .A(_001_),
    .B(_013_),
    .C(_014_),
    .Y(_000_[7])
  );
  sky130_fd_sc_hd__nor2_1 _120_ (
    .A(counter[8]),
    .B(_013_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a311oi_1 _121_ (
    .A1(counter[7]),
    .A2(counter[8]),
    .A3(_012_),
    .B1(_015_),
    .C1(_001_),
    .Y(_000_[8])
  );
  sky130_fd_sc_hd__and4_1 _122_ (
    .A(counter[7]),
    .B(counter[8]),
    .C(counter[9]),
    .D(_012_),
    .X(_016_)
  );
  sky130_fd_sc_hd__a21oi_1 _123_ (
    .A1(counter[8]),
    .A2(_013_),
    .B1(counter[9]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nor3_1 _124_ (
    .A(_001_),
    .B(_016_),
    .C(_017_),
    .Y(_000_[9])
  );
  sky130_fd_sc_hd__and2_0 _125_ (
    .A(counter[10]),
    .B(_016_),
    .X(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _126_ (
    .A(counter[10]),
    .B(_016_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor3_1 _127_ (
    .A(_001_),
    .B(_018_),
    .C(_019_),
    .Y(_000_[10])
  );
  sky130_fd_sc_hd__o21bai_1 _128_ (
    .A1(counter[11]),
    .A2(_018_),
    .B1_N(_001_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21oi_1 _129_ (
    .A1(counter[11]),
    .A2(_018_),
    .B1(_020_),
    .Y(_000_[11])
  );
  sky130_fd_sc_hd__and4_1 _130_ (
    .A(counter[10]),
    .B(counter[11]),
    .C(counter[12]),
    .D(_016_),
    .X(_021_)
  );
  sky130_fd_sc_hd__a21oi_1 _131_ (
    .A1(counter[11]),
    .A2(_018_),
    .B1(counter[12]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor3_1 _132_ (
    .A(_001_),
    .B(_021_),
    .C(_022_),
    .Y(_000_[12])
  );
  sky130_fd_sc_hd__and2_0 _133_ (
    .A(counter[13]),
    .B(_021_),
    .X(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _134_ (
    .A(counter[13]),
    .B(_021_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor3_1 _135_ (
    .A(_001_),
    .B(_023_),
    .C(_024_),
    .Y(_000_[13])
  );
  sky130_fd_sc_hd__o21bai_1 _136_ (
    .A1(counter[14]),
    .A2(_023_),
    .B1_N(_001_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a21oi_1 _137_ (
    .A1(counter[14]),
    .A2(_023_),
    .B1(_025_),
    .Y(_000_[14])
  );
  sky130_fd_sc_hd__and4_1 _138_ (
    .A(counter[13]),
    .B(counter[14]),
    .C(counter[15]),
    .D(_021_),
    .X(_026_)
  );
  sky130_fd_sc_hd__a21oi_1 _139_ (
    .A1(counter[14]),
    .A2(_023_),
    .B1(counter[15]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nor3_1 _140_ (
    .A(_001_),
    .B(_026_),
    .C(_027_),
    .Y(_000_[15])
  );
  sky130_fd_sc_hd__and2_0 _141_ (
    .A(counter[16]),
    .B(_026_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _142_ (
    .A(counter[16]),
    .B(_026_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor3_1 _143_ (
    .A(_001_),
    .B(_028_),
    .C(_029_),
    .Y(_000_[16])
  );
  sky130_fd_sc_hd__o21bai_1 _144_ (
    .A1(counter[17]),
    .A2(_028_),
    .B1_N(_001_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a21oi_1 _145_ (
    .A1(counter[17]),
    .A2(_028_),
    .B1(_030_),
    .Y(_000_[17])
  );
  sky130_fd_sc_hd__and4_1 _146_ (
    .A(counter[16]),
    .B(counter[17]),
    .C(counter[18]),
    .D(_026_),
    .X(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _147_ (
    .A1(counter[17]),
    .A2(_028_),
    .B1(counter[18]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor3_1 _148_ (
    .A(_001_),
    .B(_031_),
    .C(_032_),
    .Y(_000_[18])
  );
  sky130_fd_sc_hd__and2_0 _149_ (
    .A(counter[19]),
    .B(_031_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(counter[19]),
    .B(_031_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor3_1 _151_ (
    .A(_001_),
    .B(_033_),
    .C(_034_),
    .Y(_000_[19])
  );
  sky130_fd_sc_hd__and3_1 _152_ (
    .A(counter[19]),
    .B(counter[20]),
    .C(_031_),
    .X(_035_)
  );
  sky130_fd_sc_hd__nor2_1 _153_ (
    .A(counter[20]),
    .B(_033_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor3_1 _154_ (
    .A(_001_),
    .B(_035_),
    .C(_036_),
    .Y(_000_[20])
  );
  sky130_fd_sc_hd__o21bai_1 _155_ (
    .A1(counter[21]),
    .A2(_035_),
    .B1_N(_001_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a21oi_1 _156_ (
    .A1(counter[21]),
    .A2(_035_),
    .B1(_037_),
    .Y(_000_[21])
  );
  sky130_fd_sc_hd__and3_1 _157_ (
    .A(counter[21]),
    .B(counter[22]),
    .C(_035_),
    .X(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _158_ (
    .A1(counter[21]),
    .A2(_035_),
    .B1(counter[22]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor3_1 _159_ (
    .A(_001_),
    .B(_038_),
    .C(_039_),
    .Y(_000_[22])
  );
  sky130_fd_sc_hd__dfrtp_1 _160_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(counter[0]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _161_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(counter[1]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _162_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(counter[2]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _163_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(counter[3]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _164_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(counter[4]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _165_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(counter[5]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _166_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(counter[6]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _167_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(counter[7]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _168_ (
    .CLK(clk),
    .D(_000_[8]),
    .Q(counter[8]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _169_ (
    .CLK(clk),
    .D(_000_[9]),
    .Q(counter[9]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _170_ (
    .CLK(clk),
    .D(_000_[10]),
    .Q(counter[10]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _171_ (
    .CLK(clk),
    .D(_000_[11]),
    .Q(counter[11]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _172_ (
    .CLK(clk),
    .D(_000_[12]),
    .Q(counter[12]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _173_ (
    .CLK(clk),
    .D(_000_[13]),
    .Q(counter[13]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _174_ (
    .CLK(clk),
    .D(_000_[14]),
    .Q(counter[14]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _175_ (
    .CLK(clk),
    .D(_000_[15]),
    .Q(counter[15]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _176_ (
    .CLK(clk),
    .D(_000_[16]),
    .Q(counter[16]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _177_ (
    .CLK(clk),
    .D(_000_[17]),
    .Q(counter[17]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _178_ (
    .CLK(clk),
    .D(_000_[18]),
    .Q(counter[18]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _179_ (
    .CLK(clk),
    .D(_000_[19]),
    .Q(counter[19]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _180_ (
    .CLK(clk),
    .D(_000_[20]),
    .Q(counter[20]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _181_ (
    .CLK(clk),
    .D(_000_[21]),
    .Q(counter[21]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _182_ (
    .CLK(clk),
    .D(_000_[22]),
    .Q(counter[22]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _183_ (
    .CLK(clk),
    .D(_001_),
    .Q(hzX),
    .RESET_B(n_rst)
  );
endmodule

module hit_scanning_and_scoring(clk, n_rst, pushed, padded_notes, counter, lim, num_misses, num_hits, missed, good);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire [1:0] acc;
  wire check;
  input clk;
  wire clk;
  input [22:0] counter;
  wire [22:0] counter;
  wire [22:0] counts;
  output good;
  wire good;
  wire hit;
  input [22:0] lim;
  wire [22:0] lim;
  output missed;
  wire missed;
  input n_rst;
  wire n_rst;
  wire [22:0] next_count;
  wire [7:0] next_num_misses;
  wire next_start_count;
  output [7:0] num_hits;
  wire [7:0] num_hits;
  output [7:0] num_misses;
  wire [7:0] num_misses;
  input [39:0] padded_notes;
  wire [39:0] padded_notes;
  input pushed;
  wire pushed;
  wire start_count;
  sky130_fd_sc_hd__clkinv_1 _208_ (
    .A(counter[22]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _209_ (
    .A(lim[22]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _210_ (
    .A(check),
    .SLEEP(hit),
    .X(_013_)
  );
  sky130_fd_sc_hd__nand2b_1 _211_ (
    .A_N(hit),
    .B(check),
    .Y(_014_)
  );
  sky130_fd_sc_hd__or3_1 _212_ (
    .A(counts[21]),
    .B(counts[20]),
    .C(counts[22]),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _213_ (
    .A(counts[18]),
    .B(counts[19]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _214_ (
    .A(counts[17]),
    .B(counts[16]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nor3_1 _215_ (
    .A(counts[12]),
    .B(counts[13]),
    .C(counts[11]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor4_1 _216_ (
    .A(counts[15]),
    .B(counts[14]),
    .C(counts[9]),
    .D(counts[8]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand4_1 _217_ (
    .A(_016_),
    .B(_017_),
    .C(_018_),
    .D(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor3_1 _218_ (
    .A(counts[10]),
    .B(_015_),
    .C(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor3_1 _219_ (
    .A(counts[6]),
    .B(counts[7]),
    .C(counts[5]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2b_1 _220_ (
    .A_N(counts[4]),
    .B(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor4_1 _221_ (
    .A(counts[10]),
    .B(_015_),
    .C(_020_),
    .D(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(counts[1]),
    .B(counts[0]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _223_ (
    .A(counts[1]),
    .SLEEP(counts[0]),
    .X(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _224_ (
    .A(counts[2]),
    .B(counts[3]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _225_ (
    .A(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__and3_1 _226_ (
    .A(counts[4]),
    .B(_022_),
    .C(_027_),
    .X(_029_)
  );
  sky130_fd_sc_hd__and3_1 _227_ (
    .A(_021_),
    .B(_025_),
    .C(_029_),
    .X(_030_)
  );
  sky130_fd_sc_hd__nand3_1 _228_ (
    .A(counts[1]),
    .B(counts[2]),
    .C(counts[3]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _229_ (
    .A(_024_),
    .B(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__and3_1 _230_ (
    .A(counts[1]),
    .B(counts[0]),
    .C(counts[2]),
    .X(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _231_ (
    .A(counts[3]),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__and3_1 _232_ (
    .A(counts[2]),
    .B(_024_),
    .C(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__o22ai_1 _233_ (
    .A1(_024_),
    .A2(_030_),
    .B1(_032_),
    .B2(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand4_1 _234_ (
    .A(_021_),
    .B(_022_),
    .C(_026_),
    .D(_027_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__and4_1 _235_ (
    .A(_021_),
    .B(_023_),
    .C(_026_),
    .D(_029_),
    .X(_038_)
  );
  sky130_fd_sc_hd__o21a_1 _236_ (
    .A1(_024_),
    .A2(_030_),
    .B1(_032_),
    .X(_039_)
  );
  sky130_fd_sc_hd__a31oi_1 _237_ (
    .A1(_024_),
    .A2(_028_),
    .A3(_034_),
    .B1(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a31oi_1 _238_ (
    .A1(_024_),
    .A2(_026_),
    .A3(_027_),
    .B1(_038_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a21oi_1 _239_ (
    .A1(_024_),
    .A2(_034_),
    .B1(_032_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand3b_1 _240_ (
    .A_N(_042_),
    .B(_041_),
    .C(_040_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o2111a_1 _241_ (
    .A1(_032_),
    .A2(_034_),
    .B1(_036_),
    .C1(_037_),
    .D1(pushed),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2i_1 _242_ (
    .A0(acc[0]),
    .A1(_044_),
    .S(_014_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xnor2_1 _243_ (
    .A(num_misses[0]),
    .B(_045_),
    .Y(next_num_misses[0])
  );
  sky130_fd_sc_hd__nand2_1 _244_ (
    .A(num_misses[0]),
    .B(_044_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__and2_0 _245_ (
    .A(num_misses[0]),
    .B(num_misses[1]),
    .X(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(num_misses[0]),
    .B(acc[0]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _247_ (
    .A(num_misses[1]),
    .B(acc[1]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _248_ (
    .A(num_misses[1]),
    .B(acc[1]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _249_ (
    .A(_049_),
    .SLEEP(_050_),
    .X(_051_)
  );
  sky130_fd_sc_hd__xnor2_1 _250_ (
    .A(_048_),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _251_ (
    .A(_014_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__xor2_1 _252_ (
    .A(num_misses[1]),
    .B(_046_),
    .X(_054_)
  );
  sky130_fd_sc_hd__a21oi_1 _253_ (
    .A1(_014_),
    .A2(_054_),
    .B1(_053_),
    .Y(next_num_misses[1])
  );
  sky130_fd_sc_hd__o21ai_0 _254_ (
    .A1(_048_),
    .A2(_050_),
    .B1(_049_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__and2_0 _255_ (
    .A(_013_),
    .B(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__a31oi_1 _256_ (
    .A1(_014_),
    .A2(_044_),
    .A3(_047_),
    .B1(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xnor2_1 _257_ (
    .A(num_misses[2]),
    .B(_057_),
    .Y(next_num_misses[2])
  );
  sky130_fd_sc_hd__and3_1 _258_ (
    .A(num_misses[2]),
    .B(_044_),
    .C(_047_),
    .X(_058_)
  );
  sky130_fd_sc_hd__nor2_1 _259_ (
    .A(num_misses[3]),
    .B(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand4_1 _260_ (
    .A(num_misses[2]),
    .B(num_misses[3]),
    .C(_044_),
    .D(_047_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(_014_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a21oi_1 _262_ (
    .A1(num_misses[2]),
    .A2(_055_),
    .B1(num_misses[3]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand3_1 _263_ (
    .A(num_misses[2]),
    .B(num_misses[3]),
    .C(_055_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _264_ (
    .A(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(_013_),
    .B(_063_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__o22ai_1 _266_ (
    .A1(_059_),
    .A2(_061_),
    .B1(_062_),
    .B2(_065_),
    .Y(next_num_misses[3])
  );
  sky130_fd_sc_hd__a21boi_0 _267_ (
    .A1(_014_),
    .A2(_060_),
    .B1_N(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xor2_1 _268_ (
    .A(num_misses[4]),
    .B(_066_),
    .X(next_num_misses[4])
  );
  sky130_fd_sc_hd__a31oi_1 _269_ (
    .A1(num_misses[3]),
    .A2(num_misses[4]),
    .A3(_058_),
    .B1(num_misses[5]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(num_misses[4]),
    .B(num_misses[5]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__o21ai_0 _271_ (
    .A1(_060_),
    .A2(_068_),
    .B1(_014_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a21oi_1 _272_ (
    .A1(num_misses[4]),
    .A2(_064_),
    .B1(num_misses[5]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _273_ (
    .A(_063_),
    .B(_068_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__o32ai_1 _274_ (
    .A1(_014_),
    .A2(_070_),
    .A3(_071_),
    .B1(_067_),
    .B2(_069_),
    .Y(next_num_misses[5])
  );
  sky130_fd_sc_hd__nand3_1 _275_ (
    .A(num_misses[4]),
    .B(num_misses[5]),
    .C(_066_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _276_ (
    .A(num_misses[6]),
    .B(_072_),
    .Y(next_num_misses[6])
  );
  sky130_fd_sc_hd__nand4_1 _277_ (
    .A(num_misses[4]),
    .B(num_misses[5]),
    .C(num_misses[6]),
    .D(_014_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand3_1 _278_ (
    .A(num_misses[6]),
    .B(_013_),
    .C(_071_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21ai_0 _279_ (
    .A1(_060_),
    .A2(_073_),
    .B1(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xor2_1 _280_ (
    .A(num_misses[7]),
    .B(_075_),
    .X(next_num_misses[7])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _281_ (
    .A(start_count),
    .SLEEP(counts[0]),
    .X(next_count[0])
  );
  sky130_fd_sc_hd__nand2_1 _282_ (
    .A(start_count),
    .B(_026_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a21oi_1 _283_ (
    .A1(counts[1]),
    .A2(counts[0]),
    .B1(_076_),
    .Y(next_count[1])
  );
  sky130_fd_sc_hd__a21oi_1 _284_ (
    .A1(counts[1]),
    .A2(counts[0]),
    .B1(counts[2]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor3b_1 _285_ (
    .A(_033_),
    .B(_077_),
    .C_N(start_count),
    .Y(next_count[2])
  );
  sky130_fd_sc_hd__and4_1 _286_ (
    .A(counts[1]),
    .B(counts[0]),
    .C(counts[2]),
    .D(counts[3]),
    .X(_078_)
  );
  sky130_fd_sc_hd__nor3b_1 _287_ (
    .A(_034_),
    .B(_078_),
    .C_N(start_count),
    .Y(next_count[3])
  );
  sky130_fd_sc_hd__and2_0 _288_ (
    .A(counts[4]),
    .B(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _289_ (
    .A(counts[4]),
    .B(_078_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor3b_1 _290_ (
    .A(_079_),
    .B(_080_),
    .C_N(start_count),
    .Y(next_count[4])
  );
  sky130_fd_sc_hd__o21ai_0 _291_ (
    .A1(counts[5]),
    .A2(_079_),
    .B1(start_count),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a21oi_1 _292_ (
    .A1(counts[5]),
    .A2(_079_),
    .B1(_081_),
    .Y(next_count[5])
  );
  sky130_fd_sc_hd__and4_1 _293_ (
    .A(counts[6]),
    .B(counts[4]),
    .C(counts[5]),
    .D(_078_),
    .X(_082_)
  );
  sky130_fd_sc_hd__a21oi_1 _294_ (
    .A1(counts[5]),
    .A2(_079_),
    .B1(counts[6]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor3b_1 _295_ (
    .A(_082_),
    .B(_083_),
    .C_N(start_count),
    .Y(next_count[6])
  );
  sky130_fd_sc_hd__o21ai_0 _296_ (
    .A1(counts[7]),
    .A2(_082_),
    .B1(start_count),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a21oi_1 _297_ (
    .A1(counts[7]),
    .A2(_082_),
    .B1(_084_),
    .Y(next_count[7])
  );
  sky130_fd_sc_hd__and3_1 _298_ (
    .A(counts[7]),
    .B(counts[8]),
    .C(_082_),
    .X(_085_)
  );
  sky130_fd_sc_hd__a21oi_1 _299_ (
    .A1(counts[7]),
    .A2(_082_),
    .B1(counts[8]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor3b_1 _300_ (
    .A(_085_),
    .B(_086_),
    .C_N(start_count),
    .Y(next_count[8])
  );
  sky130_fd_sc_hd__o21ai_0 _301_ (
    .A1(counts[9]),
    .A2(_085_),
    .B1(start_count),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a21oi_1 _302_ (
    .A1(counts[9]),
    .A2(_085_),
    .B1(_087_),
    .Y(next_count[9])
  );
  sky130_fd_sc_hd__and3_1 _303_ (
    .A(counts[10]),
    .B(counts[9]),
    .C(_085_),
    .X(_088_)
  );
  sky130_fd_sc_hd__a21oi_1 _304_ (
    .A1(counts[9]),
    .A2(_085_),
    .B1(counts[10]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor3b_1 _305_ (
    .A(_088_),
    .B(_089_),
    .C_N(start_count),
    .Y(next_count[10])
  );
  sky130_fd_sc_hd__o21ai_0 _306_ (
    .A1(counts[11]),
    .A2(_088_),
    .B1(start_count),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a21oi_1 _307_ (
    .A1(counts[11]),
    .A2(_088_),
    .B1(_090_),
    .Y(next_count[11])
  );
  sky130_fd_sc_hd__and3_1 _308_ (
    .A(counts[12]),
    .B(counts[11]),
    .C(_088_),
    .X(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _309_ (
    .A1(counts[11]),
    .A2(_088_),
    .B1(counts[12]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor3b_1 _310_ (
    .A(_091_),
    .B(_092_),
    .C_N(start_count),
    .Y(next_count[12])
  );
  sky130_fd_sc_hd__and4_1 _311_ (
    .A(counts[12]),
    .B(counts[13]),
    .C(counts[11]),
    .D(_088_),
    .X(_093_)
  );
  sky130_fd_sc_hd__o21ai_0 _312_ (
    .A1(counts[13]),
    .A2(_091_),
    .B1(start_count),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _313_ (
    .A(_093_),
    .B(_094_),
    .Y(next_count[13])
  );
  sky130_fd_sc_hd__o21ai_0 _314_ (
    .A1(counts[14]),
    .A2(_093_),
    .B1(start_count),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a21oi_1 _315_ (
    .A1(counts[14]),
    .A2(_093_),
    .B1(_095_),
    .Y(next_count[14])
  );
  sky130_fd_sc_hd__a21oi_1 _316_ (
    .A1(counts[14]),
    .A2(_093_),
    .B1(counts[15]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2b_1 _317_ (
    .A_N(_096_),
    .B(start_count),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a31oi_1 _318_ (
    .A1(counts[15]),
    .A2(counts[14]),
    .A3(_093_),
    .B1(_097_),
    .Y(next_count[15])
  );
  sky130_fd_sc_hd__and4_1 _319_ (
    .A(counts[15]),
    .B(counts[14]),
    .C(counts[16]),
    .D(_093_),
    .X(_098_)
  );
  sky130_fd_sc_hd__a31oi_1 _320_ (
    .A1(counts[15]),
    .A2(counts[14]),
    .A3(_093_),
    .B1(counts[16]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor3b_1 _321_ (
    .A(_098_),
    .B(_099_),
    .C_N(start_count),
    .Y(next_count[16])
  );
  sky130_fd_sc_hd__o21ai_0 _322_ (
    .A1(counts[17]),
    .A2(_098_),
    .B1(start_count),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21oi_1 _323_ (
    .A1(counts[17]),
    .A2(_098_),
    .B1(_100_),
    .Y(next_count[17])
  );
  sky130_fd_sc_hd__and3_1 _324_ (
    .A(counts[18]),
    .B(counts[17]),
    .C(_098_),
    .X(_101_)
  );
  sky130_fd_sc_hd__a21oi_1 _325_ (
    .A1(counts[17]),
    .A2(_098_),
    .B1(counts[18]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor3b_1 _326_ (
    .A(_101_),
    .B(_102_),
    .C_N(start_count),
    .Y(next_count[18])
  );
  sky130_fd_sc_hd__and4_1 _327_ (
    .A(counts[18]),
    .B(counts[19]),
    .C(counts[17]),
    .D(_098_),
    .X(_103_)
  );
  sky130_fd_sc_hd__o21ai_0 _328_ (
    .A1(counts[19]),
    .A2(_101_),
    .B1(start_count),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(_103_),
    .B(_104_),
    .Y(next_count[19])
  );
  sky130_fd_sc_hd__o21ai_0 _330_ (
    .A1(counts[20]),
    .A2(_103_),
    .B1(start_count),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a21oi_1 _331_ (
    .A1(counts[20]),
    .A2(_103_),
    .B1(_105_),
    .Y(next_count[20])
  );
  sky130_fd_sc_hd__nand3_1 _332_ (
    .A(counts[21]),
    .B(counts[20]),
    .C(_103_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a21oi_1 _333_ (
    .A1(counts[20]),
    .A2(_103_),
    .B1(counts[21]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__and3b_1 _334_ (
    .A_N(_107_),
    .B(start_count),
    .C(_106_),
    .X(next_count[21])
  );
  sky130_fd_sc_hd__xnor2_1 _335_ (
    .A(counts[22]),
    .B(_106_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__and2_0 _336_ (
    .A(start_count),
    .B(_108_),
    .X(next_count[22])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _337_ (
    .A(pushed),
    .SLEEP(start_count),
    .X(missed)
  );
  sky130_fd_sc_hd__nor4_1 _338_ (
    .A(counter[5]),
    .B(counter[4]),
    .C(counter[7]),
    .D(counter[6]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nor3_1 _339_ (
    .A(counter[16]),
    .B(counter[19]),
    .C(counter[20]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor4_1 _340_ (
    .A(counter[17]),
    .B(counter[18]),
    .C(counter[21]),
    .D(counter[22]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor4_1 _341_ (
    .A(counter[13]),
    .B(counter[12]),
    .C(counter[15]),
    .D(counter[14]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor4_1 _342_ (
    .A(counter[9]),
    .B(counter[8]),
    .C(counter[11]),
    .D(counter[10]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(_112_),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand3_1 _344_ (
    .A(counter[1]),
    .B(counter[3]),
    .C(_109_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nor4_1 _345_ (
    .A(counter[0]),
    .B(counter[2]),
    .C(_114_),
    .D(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand3_1 _346_ (
    .A(_110_),
    .B(_111_),
    .C(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _347_ (
    .A(start_count),
    .B(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__o21a_1 _348_ (
    .A1(lim[1]),
    .A2(lim[2]),
    .B1(lim[3]),
    .X(_119_)
  );
  sky130_fd_sc_hd__nor3_1 _349_ (
    .A(lim[4]),
    .B(lim[5]),
    .C(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__or4_1 _350_ (
    .A(lim[4]),
    .B(lim[5]),
    .C(lim[6]),
    .D(_119_),
    .X(_121_)
  );
  sky130_fd_sc_hd__nor3_1 _351_ (
    .A(lim[7]),
    .B(lim[8]),
    .C(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__or4_1 _352_ (
    .A(lim[7]),
    .B(lim[8]),
    .C(lim[9]),
    .D(_121_),
    .X(_123_)
  );
  sky130_fd_sc_hd__nor3_1 _353_ (
    .A(lim[10]),
    .B(lim[11]),
    .C(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__or4_1 _354_ (
    .A(lim[10]),
    .B(lim[11]),
    .C(lim[12]),
    .D(_123_),
    .X(_125_)
  );
  sky130_fd_sc_hd__nor3_1 _355_ (
    .A(lim[13]),
    .B(lim[14]),
    .C(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__or4_1 _356_ (
    .A(lim[13]),
    .B(lim[14]),
    .C(lim[15]),
    .D(_125_),
    .X(_127_)
  );
  sky130_fd_sc_hd__nor3_1 _357_ (
    .A(lim[16]),
    .B(lim[17]),
    .C(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__or4_1 _358_ (
    .A(lim[16]),
    .B(lim[17]),
    .C(lim[18]),
    .D(_127_),
    .X(_129_)
  );
  sky130_fd_sc_hd__nor2_1 _359_ (
    .A(lim[19]),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor4_1 _360_ (
    .A(lim[19]),
    .B(lim[20]),
    .C(lim[21]),
    .D(_129_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o31a_1 _361_ (
    .A1(lim[19]),
    .A2(lim[20]),
    .A3(_129_),
    .B1(lim[21]),
    .X(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _362_ (
    .A(_131_),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xnor2_1 _363_ (
    .A(counter[21]),
    .B(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__xnor2_1 _364_ (
    .A(lim[19]),
    .B(_129_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__xnor2_1 _365_ (
    .A(counter[19]),
    .B(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__o21ai_0 _366_ (
    .A1(counter[22]),
    .A2(_012_),
    .B1(_131_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__xnor3_1 _367_ (
    .A(counter[20]),
    .B(lim[20]),
    .C(_130_),
    .X(_138_)
  );
  sky130_fd_sc_hd__nand3_1 _368_ (
    .A(_136_),
    .B(_137_),
    .C(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__or3_1 _369_ (
    .A(counter[22]),
    .B(_012_),
    .C(_131_),
    .X(_140_)
  );
  sky130_fd_sc_hd__xor2_1 _370_ (
    .A(lim[18]),
    .B(_128_),
    .X(_141_)
  );
  sky130_fd_sc_hd__xnor2_1 _371_ (
    .A(counter[18]),
    .B(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__o21ai_0 _372_ (
    .A1(lim[16]),
    .A2(_127_),
    .B1(lim[17]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2b_1 _373_ (
    .A_N(_128_),
    .B(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__xnor2_1 _374_ (
    .A(counter[17]),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__xor2_1 _375_ (
    .A(lim[16]),
    .B(_127_),
    .X(_146_)
  );
  sky130_fd_sc_hd__xnor2_1 _376_ (
    .A(counter[16]),
    .B(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__xnor2_1 _377_ (
    .A(lim[15]),
    .B(_126_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__xnor2_1 _378_ (
    .A(counter[15]),
    .B(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o21a_1 _379_ (
    .A1(lim[13]),
    .A2(_125_),
    .B1(lim[14]),
    .X(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _380_ (
    .A(_126_),
    .B(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__xnor2_1 _381_ (
    .A(counter[14]),
    .B(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__xnor2_1 _382_ (
    .A(lim[13]),
    .B(_125_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o21a_1 _383_ (
    .A1(lim[10]),
    .A2(_123_),
    .B1(lim[11]),
    .X(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _384_ (
    .A(_124_),
    .B(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__xnor2_1 _385_ (
    .A(counter[11]),
    .B(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__xnor2_1 _386_ (
    .A(lim[10]),
    .B(_123_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__xnor2_1 _387_ (
    .A(counter[10]),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__xor2_1 _388_ (
    .A(lim[9]),
    .B(_122_),
    .X(_159_)
  );
  sky130_fd_sc_hd__xnor2_1 _389_ (
    .A(counter[9]),
    .B(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__o21a_1 _390_ (
    .A1(lim[7]),
    .A2(_121_),
    .B1(lim[8]),
    .X(_161_)
  );
  sky130_fd_sc_hd__nor2_1 _391_ (
    .A(_122_),
    .B(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__xor2_1 _392_ (
    .A(counter[8]),
    .B(_162_),
    .X(_163_)
  );
  sky130_fd_sc_hd__xnor2_1 _393_ (
    .A(lim[7]),
    .B(_121_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _394_ (
    .A(counter[7]),
    .SLEEP(_164_),
    .X(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _395_ (
    .A(counter[7]),
    .B(_164_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__xnor2_1 _396_ (
    .A(counter[0]),
    .B(lim[0]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__xor2_1 _397_ (
    .A(counter[1]),
    .B(lim[1]),
    .X(_168_)
  );
  sky130_fd_sc_hd__o2111ai_1 _398_ (
    .A1(_011_),
    .A2(lim[22]),
    .B1(padded_notes[37]),
    .C1(_167_),
    .D1(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__xor2_1 _399_ (
    .A(lim[1]),
    .B(lim[2]),
    .X(_170_)
  );
  sky130_fd_sc_hd__xnor2_1 _400_ (
    .A(counter[2]),
    .B(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor3_1 _401_ (
    .A(lim[1]),
    .B(lim[2]),
    .C(lim[3]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor2_1 _402_ (
    .A(_119_),
    .B(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__xor2_1 _403_ (
    .A(counter[3]),
    .B(_173_),
    .X(_174_)
  );
  sky130_fd_sc_hd__xor2_1 _404_ (
    .A(lim[4]),
    .B(_119_),
    .X(_175_)
  );
  sky130_fd_sc_hd__xnor2_1 _405_ (
    .A(counter[4]),
    .B(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__or4_1 _406_ (
    .A(_169_),
    .B(_171_),
    .C(_174_),
    .D(_176_),
    .X(_177_)
  );
  sky130_fd_sc_hd__o21a_1 _407_ (
    .A1(lim[4]),
    .A2(_119_),
    .B1(lim[5]),
    .X(_178_)
  );
  sky130_fd_sc_hd__nor2_1 _408_ (
    .A(_120_),
    .B(_178_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__xnor2_1 _409_ (
    .A(counter[5]),
    .B(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__xnor2_1 _410_ (
    .A(lim[6]),
    .B(_120_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__xnor2_1 _411_ (
    .A(counter[6]),
    .B(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a2111oi_0 _412_ (
    .A1(_165_),
    .A2(_166_),
    .B1(_177_),
    .C1(_180_),
    .D1(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nand4_1 _413_ (
    .A(_158_),
    .B(_160_),
    .C(_163_),
    .D(_183_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__xnor2_1 _414_ (
    .A(lim[12]),
    .B(_124_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__xnor2_1 _415_ (
    .A(counter[12]),
    .B(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__xnor2_1 _416_ (
    .A(counter[13]),
    .B(_153_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__or4b_1 _417_ (
    .A(_156_),
    .B(_184_),
    .C(_186_),
    .D_N(_187_),
    .X(_188_)
  );
  sky130_fd_sc_hd__nor4_1 _418_ (
    .A(_147_),
    .B(_149_),
    .C(_152_),
    .D(_188_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nand4_1 _419_ (
    .A(_140_),
    .B(_142_),
    .C(_145_),
    .D(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__o31ai_1 _420_ (
    .A1(_134_),
    .A2(_139_),
    .A3(_190_),
    .B1(_118_),
    .Y(next_start_count)
  );
  sky130_fd_sc_hd__and2_0 _421_ (
    .A(pushed),
    .B(start_count),
    .X(good)
  );
  sky130_fd_sc_hd__and2_0 _422_ (
    .A(pushed),
    .B(_043_),
    .X(_191_)
  );
  sky130_fd_sc_hd__mux2_1 _423_ (
    .A0(acc[0]),
    .A1(_040_),
    .S(_191_),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _424_ (
    .A0(acc[1]),
    .A1(_041_),
    .S(_191_),
    .X(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _425_ (
    .A(check),
    .B(hit),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand3_1 _426_ (
    .A(check),
    .B(hit),
    .C(acc[0]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__xnor2_1 _427_ (
    .A(num_hits[0]),
    .B(_193_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xor2_1 _428_ (
    .A(acc[1]),
    .B(num_hits[1]),
    .X(_194_)
  );
  sky130_fd_sc_hd__and3_1 _429_ (
    .A(acc[0]),
    .B(num_hits[0]),
    .C(_194_),
    .X(_195_)
  );
  sky130_fd_sc_hd__a21oi_1 _430_ (
    .A1(acc[0]),
    .A2(num_hits[0]),
    .B1(_194_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nand2_1 _431_ (
    .A(num_hits[1]),
    .B(_192_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o31ai_1 _432_ (
    .A1(_192_),
    .A2(_195_),
    .A3(_196_),
    .B1(_197_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a21oi_1 _433_ (
    .A1(acc[1]),
    .A2(num_hits[1]),
    .B1(_195_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor2_1 _434_ (
    .A(_192_),
    .B(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__and2_0 _435_ (
    .A(num_hits[2]),
    .B(_199_),
    .X(_200_)
  );
  sky130_fd_sc_hd__nor2_1 _436_ (
    .A(num_hits[2]),
    .B(_199_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nor2_1 _437_ (
    .A(_200_),
    .B(_201_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xor2_1 _438_ (
    .A(num_hits[3]),
    .B(_200_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand3_1 _439_ (
    .A(num_hits[3]),
    .B(num_hits[4]),
    .C(_200_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__clkinv_1 _440_ (
    .A(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__a21oi_1 _441_ (
    .A1(num_hits[3]),
    .A2(_200_),
    .B1(num_hits[4]),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor2_1 _442_ (
    .A(_203_),
    .B(_204_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _443_ (
    .A(num_hits[5]),
    .B(_203_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__xnor2_1 _444_ (
    .A(num_hits[5]),
    .B(_202_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand3_1 _445_ (
    .A(num_hits[5]),
    .B(num_hits[6]),
    .C(_203_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__xnor2_1 _446_ (
    .A(num_hits[6]),
    .B(_205_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _447_ (
    .A(num_hits[7]),
    .B(_206_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _448_ (
    .A(hit),
    .B(_191_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nor2_1 _449_ (
    .A(check),
    .B(_207_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__dfrtp_1 _450_ (
    .CLK(clk),
    .D(_000_),
    .Q(acc[0]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _451_ (
    .CLK(clk),
    .D(_001_),
    .Q(acc[1]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _452_ (
    .CLK(clk),
    .D(next_num_misses[0]),
    .Q(num_misses[0]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _453_ (
    .CLK(clk),
    .D(next_num_misses[1]),
    .Q(num_misses[1]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _454_ (
    .CLK(clk),
    .D(next_num_misses[2]),
    .Q(num_misses[2]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _455_ (
    .CLK(clk),
    .D(next_num_misses[3]),
    .Q(num_misses[3]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _456_ (
    .CLK(clk),
    .D(next_num_misses[4]),
    .Q(num_misses[4]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _457_ (
    .CLK(clk),
    .D(next_num_misses[5]),
    .Q(num_misses[5]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _458_ (
    .CLK(clk),
    .D(next_num_misses[6]),
    .Q(num_misses[6]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _459_ (
    .CLK(clk),
    .D(next_num_misses[7]),
    .Q(num_misses[7]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _460_ (
    .CLK(clk),
    .D(_002_),
    .Q(num_hits[0]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _461_ (
    .CLK(clk),
    .D(_003_),
    .Q(num_hits[1]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _462_ (
    .CLK(clk),
    .D(_004_),
    .Q(num_hits[2]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _463_ (
    .CLK(clk),
    .D(_005_),
    .Q(num_hits[3]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _464_ (
    .CLK(clk),
    .D(_006_),
    .Q(num_hits[4]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _465_ (
    .CLK(clk),
    .D(_007_),
    .Q(num_hits[5]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _466_ (
    .CLK(clk),
    .D(_008_),
    .Q(num_hits[6]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _467_ (
    .CLK(clk),
    .D(_009_),
    .Q(num_hits[7]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _468_ (
    .CLK(clk),
    .D(_010_),
    .Q(hit),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _469_ (
    .CLK(clk),
    .D(next_count[0]),
    .Q(counts[0]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _470_ (
    .CLK(clk),
    .D(next_count[1]),
    .Q(counts[1]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _471_ (
    .CLK(clk),
    .D(next_count[2]),
    .Q(counts[2]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _472_ (
    .CLK(clk),
    .D(next_count[3]),
    .Q(counts[3]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _473_ (
    .CLK(clk),
    .D(next_count[4]),
    .Q(counts[4]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _474_ (
    .CLK(clk),
    .D(next_count[5]),
    .Q(counts[5]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _475_ (
    .CLK(clk),
    .D(next_count[6]),
    .Q(counts[6]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _476_ (
    .CLK(clk),
    .D(next_count[7]),
    .Q(counts[7]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _477_ (
    .CLK(clk),
    .D(next_count[8]),
    .Q(counts[8]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _478_ (
    .CLK(clk),
    .D(next_count[9]),
    .Q(counts[9]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _479_ (
    .CLK(clk),
    .D(next_count[10]),
    .Q(counts[10]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _480_ (
    .CLK(clk),
    .D(next_count[11]),
    .Q(counts[11]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _481_ (
    .CLK(clk),
    .D(next_count[12]),
    .Q(counts[12]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _482_ (
    .CLK(clk),
    .D(next_count[13]),
    .Q(counts[13]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _483_ (
    .CLK(clk),
    .D(next_count[14]),
    .Q(counts[14]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _484_ (
    .CLK(clk),
    .D(next_count[15]),
    .Q(counts[15]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _485_ (
    .CLK(clk),
    .D(next_count[16]),
    .Q(counts[16]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _486_ (
    .CLK(clk),
    .D(next_count[17]),
    .Q(counts[17]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _487_ (
    .CLK(clk),
    .D(next_count[18]),
    .Q(counts[18]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _488_ (
    .CLK(clk),
    .D(next_count[19]),
    .Q(counts[19]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _489_ (
    .CLK(clk),
    .D(next_count[20]),
    .Q(counts[20]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _490_ (
    .CLK(clk),
    .D(next_count[21]),
    .Q(counts[21]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _491_ (
    .CLK(clk),
    .D(next_count[22]),
    .Q(counts[22]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _492_ (
    .CLK(clk),
    .D(next_start_count),
    .Q(start_count),
    .RESET_B(n_rst)
  );
  negedge_det check_hit (
    .clk(clk),
    .in(start_count),
    .n_rst(n_rst),
    .neg_edge(check)
  );
endmodule

module main_game(notes1, notes2, mode, clk, n_rst, button_1, button_2, diff, out, num_misses, num_hits, score, hit, missed);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  input button_1;
  wire button_1;
  input button_2;
  wire button_2;
  input clk;
  wire clk;
  wire [22:0] counter;
  input [22:0] diff;
  wire [22:0] diff;
  output hit;
  wire hit;
  wire hit_1;
  wire hit_2;
  output missed;
  wire missed;
  wire missed_1;
  wire missed_2;
  input [2:0] mode;
  wire [2:0] mode;
  input n_rst;
  wire n_rst;
  input [31:0] notes1;
  wire [31:0] notes1;
  input [31:0] notes2;
  wire [31:0] notes2;
  output [7:0] num_hits;
  wire [7:0] num_hits;
  wire [7:0] num_hits_1;
  wire [7:0] num_hits_2;
  output [7:0] num_misses;
  wire [7:0] num_misses;
  wire [7:0] num_misses_1;
  wire [7:0] num_misses_2;
  output [15:0] out;
  wire [15:0] out;
  wire [39:0] padded_notes1;
  wire [39:0] padded_notes2;
  wire pushed_1;
  wire pushed_2;
  output [7:0] score;
  wire [7:0] score;
  wire scroll;
  sky130_fd_sc_hd__nand2_1 _054_ (
    .A(num_misses_2[0]),
    .B(num_misses_1[0]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _055_ (
    .A(num_misses_2[0]),
    .B(num_misses_1[0]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _056_ (
    .A(_028_),
    .Y(num_misses[0])
  );
  sky130_fd_sc_hd__nand2_1 _057_ (
    .A(num_hits_2[0]),
    .B(num_hits_1[0]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xor2_1 _058_ (
    .A(num_hits_2[0]),
    .B(num_hits_1[0]),
    .X(num_hits[0])
  );
  sky130_fd_sc_hd__nor2_1 _059_ (
    .A(_028_),
    .B(num_hits[0]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _060_ (
    .A(_028_),
    .B(num_hits[0]),
    .Y(score[0])
  );
  sky130_fd_sc_hd__nand2_1 _061_ (
    .A(num_misses_2[1]),
    .B(num_misses_1[1]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _062_ (
    .A(num_misses_2[1]),
    .B(num_misses_1[1]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xor2_1 _063_ (
    .A(num_misses_2[1]),
    .B(num_misses_1[1]),
    .X(_033_)
  );
  sky130_fd_sc_hd__xnor2_1 _064_ (
    .A(_027_),
    .B(_033_),
    .Y(num_misses[1])
  );
  sky130_fd_sc_hd__o21ai_0 _065_ (
    .A1(_027_),
    .A2(_032_),
    .B1(_031_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xor2_1 _066_ (
    .A(num_misses_2[2]),
    .B(num_misses_1[2]),
    .X(_035_)
  );
  sky130_fd_sc_hd__xnor2_1 _067_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _068_ (
    .A(_036_),
    .Y(num_misses[2])
  );
  sky130_fd_sc_hd__maj3_1 _069_ (
    .A(num_misses_2[2]),
    .B(num_misses_1[2]),
    .C(_034_),
    .X(_037_)
  );
  sky130_fd_sc_hd__xor2_1 _070_ (
    .A(num_misses_2[3]),
    .B(num_misses_1[3]),
    .X(_038_)
  );
  sky130_fd_sc_hd__xnor2_1 _071_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _072_ (
    .A(_039_),
    .Y(num_misses[3])
  );
  sky130_fd_sc_hd__maj3_1 _073_ (
    .A(num_misses_2[3]),
    .B(num_misses_1[3]),
    .C(_037_),
    .X(_040_)
  );
  sky130_fd_sc_hd__xor2_1 _074_ (
    .A(num_misses_2[4]),
    .B(num_misses_1[4]),
    .X(_041_)
  );
  sky130_fd_sc_hd__xnor2_1 _075_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _076_ (
    .A(_042_),
    .Y(num_misses[4])
  );
  sky130_fd_sc_hd__maj3_1 _077_ (
    .A(num_misses_2[4]),
    .B(num_misses_1[4]),
    .C(_040_),
    .X(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _078_ (
    .A(num_misses_2[5]),
    .B(num_misses_1[5]),
    .X(_044_)
  );
  sky130_fd_sc_hd__xnor2_1 _079_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__clkinv_1 _080_ (
    .A(_045_),
    .Y(num_misses[5])
  );
  sky130_fd_sc_hd__maj3_1 _081_ (
    .A(num_misses_2[5]),
    .B(num_misses_1[5]),
    .C(_043_),
    .X(_046_)
  );
  sky130_fd_sc_hd__xor2_1 _082_ (
    .A(num_misses_2[6]),
    .B(num_misses_1[6]),
    .X(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _083_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _084_ (
    .A(_048_),
    .Y(num_misses[6])
  );
  sky130_fd_sc_hd__maj3_1 _085_ (
    .A(num_misses_2[6]),
    .B(num_misses_1[6]),
    .C(_046_),
    .X(_049_)
  );
  sky130_fd_sc_hd__xnor2_1 _086_ (
    .A(num_misses_2[7]),
    .B(num_misses_1[7]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__xnor2_1 _087_ (
    .A(_049_),
    .B(_050_),
    .Y(num_misses[7])
  );
  sky130_fd_sc_hd__nand2_1 _088_ (
    .A(num_hits_2[1]),
    .B(num_hits_1[1]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _089_ (
    .A(num_hits_2[1]),
    .B(num_hits_1[1]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__xor2_1 _090_ (
    .A(num_hits_2[1]),
    .B(num_hits_1[1]),
    .X(_053_)
  );
  sky130_fd_sc_hd__xnor2_1 _091_ (
    .A(_029_),
    .B(_053_),
    .Y(num_hits[1])
  );
  sky130_fd_sc_hd__o21ai_0 _092_ (
    .A1(_029_),
    .A2(_052_),
    .B1(_051_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xnor2_1 _093_ (
    .A(num_hits_2[2]),
    .B(num_hits_1[2]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _094_ (
    .A(_000_),
    .B(_001_),
    .Y(num_hits[2])
  );
  sky130_fd_sc_hd__maj3_1 _095_ (
    .A(num_hits_2[2]),
    .B(num_hits_1[2]),
    .C(_000_),
    .X(_002_)
  );
  sky130_fd_sc_hd__xnor2_1 _096_ (
    .A(num_hits_2[3]),
    .B(num_hits_1[3]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xnor2_1 _097_ (
    .A(_002_),
    .B(_003_),
    .Y(num_hits[3])
  );
  sky130_fd_sc_hd__maj3_1 _098_ (
    .A(num_hits_2[3]),
    .B(num_hits_1[3]),
    .C(_002_),
    .X(_004_)
  );
  sky130_fd_sc_hd__xnor2_1 _099_ (
    .A(num_hits_2[4]),
    .B(num_hits_1[4]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xnor2_1 _100_ (
    .A(_004_),
    .B(_005_),
    .Y(num_hits[4])
  );
  sky130_fd_sc_hd__maj3_1 _101_ (
    .A(num_hits_2[4]),
    .B(num_hits_1[4]),
    .C(_004_),
    .X(_006_)
  );
  sky130_fd_sc_hd__xnor2_1 _102_ (
    .A(num_hits_2[5]),
    .B(num_hits_1[5]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xnor2_1 _103_ (
    .A(_006_),
    .B(_007_),
    .Y(num_hits[5])
  );
  sky130_fd_sc_hd__maj3_1 _104_ (
    .A(num_hits_2[5]),
    .B(num_hits_1[5]),
    .C(_006_),
    .X(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _105_ (
    .A(num_hits_2[6]),
    .B(num_hits_1[6]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xnor2_1 _106_ (
    .A(_008_),
    .B(_009_),
    .Y(num_hits[6])
  );
  sky130_fd_sc_hd__maj3_1 _107_ (
    .A(num_hits_2[6]),
    .B(num_hits_1[6]),
    .C(_008_),
    .X(_010_)
  );
  sky130_fd_sc_hd__xnor2_1 _108_ (
    .A(num_hits_2[7]),
    .B(num_hits_1[7]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _109_ (
    .A(_010_),
    .B(_011_),
    .Y(num_hits[7])
  );
  sky130_fd_sc_hd__nand2b_1 _110_ (
    .A_N(num_misses[1]),
    .B(num_hits[1]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _111_ (
    .A(num_misses[1]),
    .SLEEP(num_hits[1]),
    .X(_013_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _112_ (
    .A(_012_),
    .SLEEP(_013_),
    .X(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _113_ (
    .A(_030_),
    .B(_014_),
    .Y(score[1])
  );
  sky130_fd_sc_hd__o21ai_0 _114_ (
    .A1(_030_),
    .A2(_013_),
    .B1(_012_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__xnor2_1 _115_ (
    .A(_036_),
    .B(num_hits[2]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _116_ (
    .A(_015_),
    .B(_016_),
    .Y(score[2])
  );
  sky130_fd_sc_hd__maj3_1 _117_ (
    .A(_036_),
    .B(num_hits[2]),
    .C(_015_),
    .X(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _118_ (
    .A(_039_),
    .B(num_hits[3]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xnor2_1 _119_ (
    .A(_017_),
    .B(_018_),
    .Y(score[3])
  );
  sky130_fd_sc_hd__maj3_1 _120_ (
    .A(_039_),
    .B(num_hits[3]),
    .C(_017_),
    .X(_019_)
  );
  sky130_fd_sc_hd__xnor2_1 _121_ (
    .A(_042_),
    .B(num_hits[4]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _122_ (
    .A(_019_),
    .B(_020_),
    .Y(score[4])
  );
  sky130_fd_sc_hd__maj3_1 _123_ (
    .A(_042_),
    .B(num_hits[4]),
    .C(_019_),
    .X(_021_)
  );
  sky130_fd_sc_hd__xnor2_1 _124_ (
    .A(_045_),
    .B(num_hits[5]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _125_ (
    .A(_021_),
    .B(_022_),
    .Y(score[5])
  );
  sky130_fd_sc_hd__maj3_1 _126_ (
    .A(_045_),
    .B(num_hits[5]),
    .C(_021_),
    .X(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _127_ (
    .A(_048_),
    .B(num_hits[6]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xnor2_1 _128_ (
    .A(_023_),
    .B(_024_),
    .Y(score[6])
  );
  sky130_fd_sc_hd__maj3_1 _129_ (
    .A(_048_),
    .B(num_hits[6]),
    .C(_023_),
    .X(_025_)
  );
  sky130_fd_sc_hd__xnor2_1 _130_ (
    .A(num_misses[7]),
    .B(num_hits[7]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xor2_1 _131_ (
    .A(_025_),
    .B(_026_),
    .X(score[7])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _132_ (
    .A(missed_2),
    .SLEEP(missed_1),
    .X(missed)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _133_ (
    .A(hit_2),
    .SLEEP(hit_1),
    .X(hit)
  );
  sync_posedge edge_button_1 (
    .button(button_1),
    .clk(clk),
    .mode(mode),
    .n_rst(n_rst),
    .posout(pushed_1)
  );
  sync_posedge edge_button_2 (
    .button(button_2),
    .clk(clk),
    .mode(mode),
    .n_rst(n_rst),
    .posout(pushed_2)
  );
  scroll_and_display play_song (
    .clk(clk),
    .mode(mode),
    .n_rst(n_rst),
    .notes1(notes1),
    .notes2(notes2),
    .out(out),
    .padded_notes1(padded_notes1),
    .padded_notes2(padded_notes2),
    .scroll(scroll)
  );
  hit_scanning_and_scoring scoring_button_1 (
    .clk(clk),
    .counter(counter),
    .good(hit_1),
    .lim(diff),
    .missed(missed_1),
    .n_rst(n_rst),
    .num_hits(num_hits_1),
    .num_misses(num_misses_1),
    .padded_notes(padded_notes1),
    .pushed(pushed_1)
  );
  hit_scanning_and_scoring scoring_button_2 (
    .clk(clk),
    .counter(counter),
    .good(hit_2),
    .lim(diff),
    .missed(missed_2),
    .n_rst(n_rst),
    .num_hits(num_hits_2),
    .num_misses(num_misses_2),
    .padded_notes(padded_notes2),
    .pushed(pushed_2)
  );
  clk_div speed (
    .clk(clk),
    .counter(counter),
    .hzX(scroll),
    .lim(diff),
    .n_rst(n_rst)
  );
endmodule

module negedge_det(clk, n_rst, in, neg_edge);
  input clk;
  wire clk;
  wire edge_1;
  wire edge_2;
  input in;
  wire in;
  input n_rst;
  wire n_rst;
  output neg_edge;
  wire neg_edge;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0_ (
    .A(edge_2),
    .SLEEP(edge_1),
    .X(neg_edge)
  );
  sky130_fd_sc_hd__dfrtp_1 _1_ (
    .CLK(clk),
    .D(in),
    .Q(edge_1),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(edge_1),
    .Q(edge_2),
    .RESET_B(n_rst)
  );
endmodule

module scroll_and_display(clk, n_rst, scroll, notes1, notes2, mode, padded_notes1, padded_notes2, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  input clk;
  wire clk;
  wire [7:0] curr1;
  wire [7:0] curr2;
  input [2:0] mode;
  wire [2:0] mode;
  input n_rst;
  wire n_rst;
  input [31:0] notes1;
  wire [31:0] notes1;
  input [31:0] notes2;
  wire [31:0] notes2;
  output [15:0] out;
  wire [15:0] out;
  output [39:0] padded_notes1;
  wire [39:0] padded_notes1;
  output [39:0] padded_notes2;
  wire [39:0] padded_notes2;
  input scroll;
  wire scroll;
  sky130_fd_sc_hd__clkinv_1 _177_ (
    .A(padded_notes2[32]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__clkinv_1 _178_ (
    .A(padded_notes2[33]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__clkinv_1 _179_ (
    .A(padded_notes2[34]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _180_ (
    .A(padded_notes2[35]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__clkinv_1 _181_ (
    .A(padded_notes2[36]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__clkinv_1 _182_ (
    .A(padded_notes2[37]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__clkinv_1 _183_ (
    .A(padded_notes2[38]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__clkinv_1 _184_ (
    .A(padded_notes1[32]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _185_ (
    .A(padded_notes1[33]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _186_ (
    .A(padded_notes1[34]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _187_ (
    .A(padded_notes1[35]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__clkinv_1 _188_ (
    .A(padded_notes1[36]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _189_ (
    .A(padded_notes1[37]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__clkinv_1 _190_ (
    .A(padded_notes1[38]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__clkinv_1 _191_ (
    .A(padded_notes1[39]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _192_ (
    .A(padded_notes2[39]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor3b_1 _193_ (
    .A(mode[1]),
    .B(mode[0]),
    .C_N(mode[2]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__and3b_1 _194_ (
    .A_N(mode[2]),
    .B(mode[0]),
    .C(mode[1]),
    .X(_097_)
  );
  sky130_fd_sc_hd__a21oi_1 _195_ (
    .A1(scroll),
    .A2(_096_),
    .B1(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a22o_1 _196_ (
    .A1(notes1[0]),
    .A2(_097_),
    .B1(_098_),
    .B2(padded_notes1[0]),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _197_ (
    .A0(notes1[1]),
    .A1(padded_notes1[0]),
    .S(_096_),
    .X(_099_)
  );
  sky130_fd_sc_hd__mux2_1 _198_ (
    .A0(_099_),
    .A1(padded_notes1[1]),
    .S(_098_),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _199_ (
    .A0(notes1[2]),
    .A1(padded_notes1[1]),
    .S(_096_),
    .X(_100_)
  );
  sky130_fd_sc_hd__mux2_1 _200_ (
    .A0(_100_),
    .A1(padded_notes1[2]),
    .S(_098_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _201_ (
    .A0(notes1[3]),
    .A1(padded_notes1[2]),
    .S(_096_),
    .X(_101_)
  );
  sky130_fd_sc_hd__mux2_1 _202_ (
    .A0(_101_),
    .A1(padded_notes1[3]),
    .S(_098_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _203_ (
    .A0(notes1[4]),
    .A1(padded_notes1[3]),
    .S(_096_),
    .X(_102_)
  );
  sky130_fd_sc_hd__mux2_1 _204_ (
    .A0(_102_),
    .A1(padded_notes1[4]),
    .S(_098_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _205_ (
    .A0(notes1[5]),
    .A1(padded_notes1[4]),
    .S(_096_),
    .X(_103_)
  );
  sky130_fd_sc_hd__mux2_1 _206_ (
    .A0(_103_),
    .A1(padded_notes1[5]),
    .S(_098_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _207_ (
    .A0(notes1[6]),
    .A1(padded_notes1[5]),
    .S(_096_),
    .X(_104_)
  );
  sky130_fd_sc_hd__mux2_1 _208_ (
    .A0(_104_),
    .A1(padded_notes1[6]),
    .S(_098_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _209_ (
    .A0(notes1[7]),
    .A1(padded_notes1[6]),
    .S(_096_),
    .X(_105_)
  );
  sky130_fd_sc_hd__mux2_1 _210_ (
    .A0(_105_),
    .A1(padded_notes1[7]),
    .S(_098_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _211_ (
    .A0(notes1[8]),
    .A1(padded_notes1[7]),
    .S(_096_),
    .X(_106_)
  );
  sky130_fd_sc_hd__mux2_1 _212_ (
    .A0(_106_),
    .A1(padded_notes1[8]),
    .S(_098_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _213_ (
    .A0(notes1[9]),
    .A1(padded_notes1[8]),
    .S(_096_),
    .X(_107_)
  );
  sky130_fd_sc_hd__mux2_1 _214_ (
    .A0(_107_),
    .A1(padded_notes1[9]),
    .S(_098_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _215_ (
    .A0(notes1[10]),
    .A1(padded_notes1[9]),
    .S(_096_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2_1 _216_ (
    .A0(_108_),
    .A1(padded_notes1[10]),
    .S(_098_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _217_ (
    .A0(notes1[11]),
    .A1(padded_notes1[10]),
    .S(_096_),
    .X(_109_)
  );
  sky130_fd_sc_hd__mux2_1 _218_ (
    .A0(_109_),
    .A1(padded_notes1[11]),
    .S(_098_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _219_ (
    .A0(notes1[12]),
    .A1(padded_notes1[11]),
    .S(_096_),
    .X(_110_)
  );
  sky130_fd_sc_hd__mux2_1 _220_ (
    .A0(_110_),
    .A1(padded_notes1[12]),
    .S(_098_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _221_ (
    .A0(notes1[13]),
    .A1(padded_notes1[12]),
    .S(_096_),
    .X(_111_)
  );
  sky130_fd_sc_hd__mux2_1 _222_ (
    .A0(_111_),
    .A1(padded_notes1[13]),
    .S(_098_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _223_ (
    .A0(notes1[14]),
    .A1(padded_notes1[13]),
    .S(_096_),
    .X(_112_)
  );
  sky130_fd_sc_hd__mux2_1 _224_ (
    .A0(_112_),
    .A1(padded_notes1[14]),
    .S(_098_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _225_ (
    .A0(notes1[15]),
    .A1(padded_notes1[14]),
    .S(_096_),
    .X(_113_)
  );
  sky130_fd_sc_hd__mux2_1 _226_ (
    .A0(_113_),
    .A1(padded_notes1[15]),
    .S(_098_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _227_ (
    .A0(notes1[16]),
    .A1(padded_notes1[15]),
    .S(_096_),
    .X(_114_)
  );
  sky130_fd_sc_hd__mux2_1 _228_ (
    .A0(_114_),
    .A1(padded_notes1[16]),
    .S(_098_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _229_ (
    .A0(notes1[17]),
    .A1(padded_notes1[16]),
    .S(_096_),
    .X(_115_)
  );
  sky130_fd_sc_hd__mux2_1 _230_ (
    .A0(_115_),
    .A1(padded_notes1[17]),
    .S(_098_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _231_ (
    .A0(notes1[18]),
    .A1(padded_notes1[17]),
    .S(_096_),
    .X(_116_)
  );
  sky130_fd_sc_hd__mux2_1 _232_ (
    .A0(_116_),
    .A1(padded_notes1[18]),
    .S(_098_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _233_ (
    .A0(notes1[19]),
    .A1(padded_notes1[18]),
    .S(_096_),
    .X(_117_)
  );
  sky130_fd_sc_hd__mux2_1 _234_ (
    .A0(_117_),
    .A1(padded_notes1[19]),
    .S(_098_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _235_ (
    .A0(notes1[20]),
    .A1(padded_notes1[19]),
    .S(_096_),
    .X(_118_)
  );
  sky130_fd_sc_hd__mux2_1 _236_ (
    .A0(_118_),
    .A1(padded_notes1[20]),
    .S(_098_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _237_ (
    .A0(notes1[21]),
    .A1(padded_notes1[20]),
    .S(_096_),
    .X(_119_)
  );
  sky130_fd_sc_hd__mux2_1 _238_ (
    .A0(_119_),
    .A1(padded_notes1[21]),
    .S(_098_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _239_ (
    .A0(notes1[22]),
    .A1(padded_notes1[21]),
    .S(_096_),
    .X(_120_)
  );
  sky130_fd_sc_hd__mux2_1 _240_ (
    .A0(_120_),
    .A1(padded_notes1[22]),
    .S(_098_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _241_ (
    .A0(notes1[23]),
    .A1(padded_notes1[22]),
    .S(_096_),
    .X(_121_)
  );
  sky130_fd_sc_hd__mux2_1 _242_ (
    .A0(_121_),
    .A1(padded_notes1[23]),
    .S(_098_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _243_ (
    .A0(notes1[24]),
    .A1(padded_notes1[23]),
    .S(_096_),
    .X(_122_)
  );
  sky130_fd_sc_hd__mux2_1 _244_ (
    .A0(_122_),
    .A1(padded_notes1[24]),
    .S(_098_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _245_ (
    .A0(notes1[25]),
    .A1(padded_notes1[24]),
    .S(_096_),
    .X(_123_)
  );
  sky130_fd_sc_hd__mux2_1 _246_ (
    .A0(_123_),
    .A1(padded_notes1[25]),
    .S(_098_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _247_ (
    .A0(notes1[26]),
    .A1(padded_notes1[25]),
    .S(_096_),
    .X(_124_)
  );
  sky130_fd_sc_hd__mux2_1 _248_ (
    .A0(_124_),
    .A1(padded_notes1[26]),
    .S(_098_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _249_ (
    .A0(notes1[27]),
    .A1(padded_notes1[26]),
    .S(_096_),
    .X(_125_)
  );
  sky130_fd_sc_hd__mux2_1 _250_ (
    .A0(_125_),
    .A1(padded_notes1[27]),
    .S(_098_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _251_ (
    .A0(notes1[28]),
    .A1(padded_notes1[27]),
    .S(_096_),
    .X(_126_)
  );
  sky130_fd_sc_hd__mux2_1 _252_ (
    .A0(_126_),
    .A1(padded_notes1[28]),
    .S(_098_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _253_ (
    .A0(notes1[29]),
    .A1(padded_notes1[28]),
    .S(_096_),
    .X(_127_)
  );
  sky130_fd_sc_hd__mux2_1 _254_ (
    .A0(_127_),
    .A1(padded_notes1[29]),
    .S(_098_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _255_ (
    .A0(notes1[30]),
    .A1(padded_notes1[29]),
    .S(_096_),
    .X(_128_)
  );
  sky130_fd_sc_hd__mux2_1 _256_ (
    .A0(_128_),
    .A1(padded_notes1[30]),
    .S(_098_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _257_ (
    .A0(notes1[31]),
    .A1(padded_notes1[30]),
    .S(_096_),
    .X(_129_)
  );
  sky130_fd_sc_hd__mux2_1 _258_ (
    .A0(_129_),
    .A1(padded_notes1[31]),
    .S(_098_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(padded_notes1[31]),
    .B(_096_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__mux2i_1 _260_ (
    .A0(_130_),
    .A1(_087_),
    .S(_098_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(padded_notes1[32]),
    .B(_096_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__mux2i_1 _262_ (
    .A0(_131_),
    .A1(_088_),
    .S(_098_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(padded_notes1[33]),
    .B(_096_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__mux2i_1 _264_ (
    .A0(_132_),
    .A1(_089_),
    .S(_098_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(padded_notes1[34]),
    .B(_096_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__mux2i_1 _266_ (
    .A0(_133_),
    .A1(_090_),
    .S(_098_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(padded_notes1[35]),
    .B(_096_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__mux2i_1 _268_ (
    .A0(_134_),
    .A1(_091_),
    .S(_098_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _269_ (
    .A(padded_notes1[36]),
    .B(_096_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__mux2i_1 _270_ (
    .A0(_135_),
    .A1(_092_),
    .S(_098_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(padded_notes1[37]),
    .B(_096_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__mux2i_1 _272_ (
    .A0(_136_),
    .A1(_093_),
    .S(_098_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(padded_notes1[38]),
    .B(_096_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__mux2i_1 _274_ (
    .A0(_137_),
    .A1(_094_),
    .S(_098_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a22o_1 _275_ (
    .A1(notes2[0]),
    .A2(_097_),
    .B1(_098_),
    .B2(padded_notes2[0]),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _276_ (
    .A0(notes2[1]),
    .A1(padded_notes2[0]),
    .S(_096_),
    .X(_138_)
  );
  sky130_fd_sc_hd__mux2_1 _277_ (
    .A0(_138_),
    .A1(padded_notes2[1]),
    .S(_098_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _278_ (
    .A0(notes2[2]),
    .A1(padded_notes2[1]),
    .S(_096_),
    .X(_139_)
  );
  sky130_fd_sc_hd__mux2_1 _279_ (
    .A0(_139_),
    .A1(padded_notes2[2]),
    .S(_098_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _280_ (
    .A0(notes2[3]),
    .A1(padded_notes2[2]),
    .S(_096_),
    .X(_140_)
  );
  sky130_fd_sc_hd__mux2_1 _281_ (
    .A0(_140_),
    .A1(padded_notes2[3]),
    .S(_098_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _282_ (
    .A0(notes2[4]),
    .A1(padded_notes2[3]),
    .S(_096_),
    .X(_141_)
  );
  sky130_fd_sc_hd__mux2_1 _283_ (
    .A0(_141_),
    .A1(padded_notes2[4]),
    .S(_098_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _284_ (
    .A0(notes2[5]),
    .A1(padded_notes2[4]),
    .S(_096_),
    .X(_142_)
  );
  sky130_fd_sc_hd__mux2_1 _285_ (
    .A0(_142_),
    .A1(padded_notes2[5]),
    .S(_098_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _286_ (
    .A0(notes2[6]),
    .A1(padded_notes2[5]),
    .S(_096_),
    .X(_143_)
  );
  sky130_fd_sc_hd__mux2_1 _287_ (
    .A0(_143_),
    .A1(padded_notes2[6]),
    .S(_098_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _288_ (
    .A0(notes2[7]),
    .A1(padded_notes2[6]),
    .S(_096_),
    .X(_144_)
  );
  sky130_fd_sc_hd__mux2_1 _289_ (
    .A0(_144_),
    .A1(padded_notes2[7]),
    .S(_098_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _290_ (
    .A0(notes2[8]),
    .A1(padded_notes2[7]),
    .S(_096_),
    .X(_145_)
  );
  sky130_fd_sc_hd__mux2_1 _291_ (
    .A0(_145_),
    .A1(padded_notes2[8]),
    .S(_098_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _292_ (
    .A0(notes2[9]),
    .A1(padded_notes2[8]),
    .S(_096_),
    .X(_146_)
  );
  sky130_fd_sc_hd__mux2_1 _293_ (
    .A0(_146_),
    .A1(padded_notes2[9]),
    .S(_098_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _294_ (
    .A0(notes2[10]),
    .A1(padded_notes2[9]),
    .S(_096_),
    .X(_147_)
  );
  sky130_fd_sc_hd__mux2_1 _295_ (
    .A0(_147_),
    .A1(padded_notes2[10]),
    .S(_098_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _296_ (
    .A0(notes2[11]),
    .A1(padded_notes2[10]),
    .S(_096_),
    .X(_148_)
  );
  sky130_fd_sc_hd__mux2_1 _297_ (
    .A0(_148_),
    .A1(padded_notes2[11]),
    .S(_098_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _298_ (
    .A0(notes2[12]),
    .A1(padded_notes2[11]),
    .S(_096_),
    .X(_149_)
  );
  sky130_fd_sc_hd__mux2_1 _299_ (
    .A0(_149_),
    .A1(padded_notes2[12]),
    .S(_098_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _300_ (
    .A0(notes2[13]),
    .A1(padded_notes2[12]),
    .S(_096_),
    .X(_150_)
  );
  sky130_fd_sc_hd__mux2_1 _301_ (
    .A0(_150_),
    .A1(padded_notes2[13]),
    .S(_098_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _302_ (
    .A0(notes2[14]),
    .A1(padded_notes2[13]),
    .S(_096_),
    .X(_151_)
  );
  sky130_fd_sc_hd__mux2_1 _303_ (
    .A0(_151_),
    .A1(padded_notes2[14]),
    .S(_098_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _304_ (
    .A0(notes2[15]),
    .A1(padded_notes2[14]),
    .S(_096_),
    .X(_152_)
  );
  sky130_fd_sc_hd__mux2_1 _305_ (
    .A0(_152_),
    .A1(padded_notes2[15]),
    .S(_098_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _306_ (
    .A0(notes2[16]),
    .A1(padded_notes2[15]),
    .S(_096_),
    .X(_153_)
  );
  sky130_fd_sc_hd__mux2_1 _307_ (
    .A0(_153_),
    .A1(padded_notes2[16]),
    .S(_098_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _308_ (
    .A0(notes2[17]),
    .A1(padded_notes2[16]),
    .S(_096_),
    .X(_154_)
  );
  sky130_fd_sc_hd__mux2_1 _309_ (
    .A0(_154_),
    .A1(padded_notes2[17]),
    .S(_098_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _310_ (
    .A0(notes2[18]),
    .A1(padded_notes2[17]),
    .S(_096_),
    .X(_155_)
  );
  sky130_fd_sc_hd__mux2_1 _311_ (
    .A0(_155_),
    .A1(padded_notes2[18]),
    .S(_098_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _312_ (
    .A0(notes2[19]),
    .A1(padded_notes2[18]),
    .S(_096_),
    .X(_156_)
  );
  sky130_fd_sc_hd__mux2_1 _313_ (
    .A0(_156_),
    .A1(padded_notes2[19]),
    .S(_098_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _314_ (
    .A0(notes2[20]),
    .A1(padded_notes2[19]),
    .S(_096_),
    .X(_157_)
  );
  sky130_fd_sc_hd__mux2_1 _315_ (
    .A0(_157_),
    .A1(padded_notes2[20]),
    .S(_098_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _316_ (
    .A0(notes2[21]),
    .A1(padded_notes2[20]),
    .S(_096_),
    .X(_158_)
  );
  sky130_fd_sc_hd__mux2_1 _317_ (
    .A0(_158_),
    .A1(padded_notes2[21]),
    .S(_098_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _318_ (
    .A0(notes2[22]),
    .A1(padded_notes2[21]),
    .S(_096_),
    .X(_159_)
  );
  sky130_fd_sc_hd__mux2_1 _319_ (
    .A0(_159_),
    .A1(padded_notes2[22]),
    .S(_098_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _320_ (
    .A0(notes2[23]),
    .A1(padded_notes2[22]),
    .S(_096_),
    .X(_160_)
  );
  sky130_fd_sc_hd__mux2_1 _321_ (
    .A0(_160_),
    .A1(padded_notes2[23]),
    .S(_098_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _322_ (
    .A0(notes2[24]),
    .A1(padded_notes2[23]),
    .S(_096_),
    .X(_161_)
  );
  sky130_fd_sc_hd__mux2_1 _323_ (
    .A0(_161_),
    .A1(padded_notes2[24]),
    .S(_098_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_1 _324_ (
    .A0(notes2[25]),
    .A1(padded_notes2[24]),
    .S(_096_),
    .X(_162_)
  );
  sky130_fd_sc_hd__mux2_1 _325_ (
    .A0(_162_),
    .A1(padded_notes2[25]),
    .S(_098_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _326_ (
    .A0(notes2[26]),
    .A1(padded_notes2[25]),
    .S(_096_),
    .X(_163_)
  );
  sky130_fd_sc_hd__mux2_1 _327_ (
    .A0(_163_),
    .A1(padded_notes2[26]),
    .S(_098_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _328_ (
    .A0(notes2[27]),
    .A1(padded_notes2[26]),
    .S(_096_),
    .X(_164_)
  );
  sky130_fd_sc_hd__mux2_1 _329_ (
    .A0(_164_),
    .A1(padded_notes2[27]),
    .S(_098_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _330_ (
    .A0(notes2[28]),
    .A1(padded_notes2[27]),
    .S(_096_),
    .X(_165_)
  );
  sky130_fd_sc_hd__mux2_1 _331_ (
    .A0(_165_),
    .A1(padded_notes2[28]),
    .S(_098_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2_1 _332_ (
    .A0(notes2[29]),
    .A1(padded_notes2[28]),
    .S(_096_),
    .X(_166_)
  );
  sky130_fd_sc_hd__mux2_1 _333_ (
    .A0(_166_),
    .A1(padded_notes2[29]),
    .S(_098_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _334_ (
    .A0(notes2[30]),
    .A1(padded_notes2[29]),
    .S(_096_),
    .X(_167_)
  );
  sky130_fd_sc_hd__mux2_1 _335_ (
    .A0(_167_),
    .A1(padded_notes2[30]),
    .S(_098_),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _336_ (
    .A0(notes2[31]),
    .A1(padded_notes2[30]),
    .S(_096_),
    .X(_168_)
  );
  sky130_fd_sc_hd__mux2_1 _337_ (
    .A0(_168_),
    .A1(padded_notes2[31]),
    .S(_098_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(padded_notes2[31]),
    .B(_096_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__mux2i_1 _339_ (
    .A0(_169_),
    .A1(_080_),
    .S(_098_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _340_ (
    .A(padded_notes2[32]),
    .B(_096_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__mux2i_1 _341_ (
    .A0(_170_),
    .A1(_081_),
    .S(_098_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(padded_notes2[33]),
    .B(_096_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__mux2i_1 _343_ (
    .A0(_171_),
    .A1(_082_),
    .S(_098_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(padded_notes2[34]),
    .B(_096_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__mux2i_1 _345_ (
    .A0(_172_),
    .A1(_083_),
    .S(_098_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(padded_notes2[35]),
    .B(_096_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__mux2i_1 _347_ (
    .A0(_173_),
    .A1(_084_),
    .S(_098_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(padded_notes2[36]),
    .B(_096_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__mux2i_1 _349_ (
    .A0(_174_),
    .A1(_085_),
    .S(_098_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _350_ (
    .A(padded_notes2[37]),
    .B(_096_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__mux2i_1 _351_ (
    .A0(_175_),
    .A1(_086_),
    .S(_098_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _352_ (
    .A(padded_notes2[38]),
    .B(_096_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__mux2i_1 _353_ (
    .A0(_176_),
    .A1(_095_),
    .S(_098_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__dfrtp_1 _354_ (
    .CLK(clk),
    .D(_000_),
    .Q(padded_notes1[0]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _355_ (
    .CLK(clk),
    .D(_001_),
    .Q(padded_notes1[1]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _356_ (
    .CLK(clk),
    .D(_002_),
    .Q(padded_notes1[2]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _357_ (
    .CLK(clk),
    .D(_003_),
    .Q(padded_notes1[3]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _358_ (
    .CLK(clk),
    .D(_004_),
    .Q(padded_notes1[4]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _359_ (
    .CLK(clk),
    .D(_005_),
    .Q(padded_notes1[5]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _360_ (
    .CLK(clk),
    .D(_006_),
    .Q(padded_notes1[6]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _361_ (
    .CLK(clk),
    .D(_007_),
    .Q(padded_notes1[7]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _362_ (
    .CLK(clk),
    .D(_008_),
    .Q(padded_notes1[8]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _363_ (
    .CLK(clk),
    .D(_009_),
    .Q(padded_notes1[9]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _364_ (
    .CLK(clk),
    .D(_010_),
    .Q(padded_notes1[10]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _365_ (
    .CLK(clk),
    .D(_011_),
    .Q(padded_notes1[11]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _366_ (
    .CLK(clk),
    .D(_012_),
    .Q(padded_notes1[12]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _367_ (
    .CLK(clk),
    .D(_013_),
    .Q(padded_notes1[13]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _368_ (
    .CLK(clk),
    .D(_014_),
    .Q(padded_notes1[14]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _369_ (
    .CLK(clk),
    .D(_015_),
    .Q(padded_notes1[15]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _370_ (
    .CLK(clk),
    .D(_016_),
    .Q(padded_notes1[16]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _371_ (
    .CLK(clk),
    .D(_017_),
    .Q(padded_notes1[17]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _372_ (
    .CLK(clk),
    .D(_018_),
    .Q(padded_notes1[18]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _373_ (
    .CLK(clk),
    .D(_019_),
    .Q(padded_notes1[19]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _374_ (
    .CLK(clk),
    .D(_020_),
    .Q(padded_notes1[20]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _375_ (
    .CLK(clk),
    .D(_021_),
    .Q(padded_notes1[21]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _376_ (
    .CLK(clk),
    .D(_022_),
    .Q(padded_notes1[22]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _377_ (
    .CLK(clk),
    .D(_023_),
    .Q(padded_notes1[23]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _378_ (
    .CLK(clk),
    .D(_024_),
    .Q(padded_notes1[24]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _379_ (
    .CLK(clk),
    .D(_025_),
    .Q(padded_notes1[25]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _380_ (
    .CLK(clk),
    .D(_026_),
    .Q(padded_notes1[26]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _381_ (
    .CLK(clk),
    .D(_027_),
    .Q(padded_notes1[27]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _382_ (
    .CLK(clk),
    .D(_028_),
    .Q(padded_notes1[28]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _383_ (
    .CLK(clk),
    .D(_029_),
    .Q(padded_notes1[29]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _384_ (
    .CLK(clk),
    .D(_030_),
    .Q(padded_notes1[30]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _385_ (
    .CLK(clk),
    .D(_031_),
    .Q(padded_notes1[31]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _386_ (
    .CLK(clk),
    .D(_032_),
    .Q(padded_notes1[32]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _387_ (
    .CLK(clk),
    .D(_033_),
    .Q(padded_notes1[33]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _388_ (
    .CLK(clk),
    .D(_034_),
    .Q(padded_notes1[34]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _389_ (
    .CLK(clk),
    .D(_035_),
    .Q(padded_notes1[35]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _390_ (
    .CLK(clk),
    .D(_036_),
    .Q(padded_notes1[36]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _391_ (
    .CLK(clk),
    .D(_037_),
    .Q(padded_notes1[37]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _392_ (
    .CLK(clk),
    .D(_038_),
    .Q(padded_notes1[38]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _393_ (
    .CLK(clk),
    .D(_039_),
    .Q(padded_notes1[39]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _394_ (
    .CLK(clk),
    .D(_040_),
    .Q(padded_notes2[0]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _395_ (
    .CLK(clk),
    .D(_041_),
    .Q(padded_notes2[1]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _396_ (
    .CLK(clk),
    .D(_042_),
    .Q(padded_notes2[2]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _397_ (
    .CLK(clk),
    .D(_043_),
    .Q(padded_notes2[3]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _398_ (
    .CLK(clk),
    .D(_044_),
    .Q(padded_notes2[4]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _399_ (
    .CLK(clk),
    .D(_045_),
    .Q(padded_notes2[5]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _400_ (
    .CLK(clk),
    .D(_046_),
    .Q(padded_notes2[6]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _401_ (
    .CLK(clk),
    .D(_047_),
    .Q(padded_notes2[7]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _402_ (
    .CLK(clk),
    .D(_048_),
    .Q(padded_notes2[8]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _403_ (
    .CLK(clk),
    .D(_049_),
    .Q(padded_notes2[9]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _404_ (
    .CLK(clk),
    .D(_050_),
    .Q(padded_notes2[10]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _405_ (
    .CLK(clk),
    .D(_051_),
    .Q(padded_notes2[11]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _406_ (
    .CLK(clk),
    .D(_052_),
    .Q(padded_notes2[12]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _407_ (
    .CLK(clk),
    .D(_053_),
    .Q(padded_notes2[13]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _408_ (
    .CLK(clk),
    .D(_054_),
    .Q(padded_notes2[14]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _409_ (
    .CLK(clk),
    .D(_055_),
    .Q(padded_notes2[15]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _410_ (
    .CLK(clk),
    .D(_056_),
    .Q(padded_notes2[16]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _411_ (
    .CLK(clk),
    .D(_057_),
    .Q(padded_notes2[17]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _412_ (
    .CLK(clk),
    .D(_058_),
    .Q(padded_notes2[18]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _413_ (
    .CLK(clk),
    .D(_059_),
    .Q(padded_notes2[19]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _414_ (
    .CLK(clk),
    .D(_060_),
    .Q(padded_notes2[20]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _415_ (
    .CLK(clk),
    .D(_061_),
    .Q(padded_notes2[21]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _416_ (
    .CLK(clk),
    .D(_062_),
    .Q(padded_notes2[22]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _417_ (
    .CLK(clk),
    .D(_063_),
    .Q(padded_notes2[23]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _418_ (
    .CLK(clk),
    .D(_064_),
    .Q(padded_notes2[24]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _419_ (
    .CLK(clk),
    .D(_065_),
    .Q(padded_notes2[25]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _420_ (
    .CLK(clk),
    .D(_066_),
    .Q(padded_notes2[26]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _421_ (
    .CLK(clk),
    .D(_067_),
    .Q(padded_notes2[27]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _422_ (
    .CLK(clk),
    .D(_068_),
    .Q(padded_notes2[28]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _423_ (
    .CLK(clk),
    .D(_069_),
    .Q(padded_notes2[29]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _424_ (
    .CLK(clk),
    .D(_070_),
    .Q(padded_notes2[30]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _425_ (
    .CLK(clk),
    .D(_071_),
    .Q(padded_notes2[31]),
    .SET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _426_ (
    .CLK(clk),
    .D(_072_),
    .Q(padded_notes2[32]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _427_ (
    .CLK(clk),
    .D(_073_),
    .Q(padded_notes2[33]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _428_ (
    .CLK(clk),
    .D(_074_),
    .Q(padded_notes2[34]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _429_ (
    .CLK(clk),
    .D(_075_),
    .Q(padded_notes2[35]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _430_ (
    .CLK(clk),
    .D(_076_),
    .Q(padded_notes2[36]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _431_ (
    .CLK(clk),
    .D(_077_),
    .Q(padded_notes2[37]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _432_ (
    .CLK(clk),
    .D(_078_),
    .Q(padded_notes2[38]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _433_ (
    .CLK(clk),
    .D(_079_),
    .Q(padded_notes2[39]),
    .RESET_B(n_rst)
  );
  assign curr1 = padded_notes1[38:31];
  assign curr2 = padded_notes2[38:31];
  assign out = { padded_notes1[38], padded_notes2[38], padded_notes1[37], padded_notes2[37], padded_notes1[36], padded_notes2[36], padded_notes1[35], padded_notes2[35], padded_notes1[34], padded_notes2[34], padded_notes1[33], padded_notes2[33], padded_notes1[32], padded_notes2[32], padded_notes1[31], padded_notes2[31] };
endmodule

module sync_posedge(clk, n_rst, button, mode, posout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire accept;
  input button;
  wire button;
  input clk;
  wire clk;
  wire [5:0] counter;
  wire edge_1;
  wire edge_2;
  input [2:0] mode;
  wire [2:0] mode;
  input n_rst;
  wire n_rst;
  wire [5:0] next_count;
  output posout;
  wire posout;
  wire sync_out;
  sky130_fd_sc_hd__nor3b_1 _13_ (
    .A(mode[1]),
    .B(mode[0]),
    .C_N(mode[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand2b_1 _14_ (
    .A_N(accept),
    .B(_01_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _15_ (
    .A(counter[0]),
    .B(_02_),
    .Y(next_count[0])
  );
  sky130_fd_sc_hd__xnor2_1 _16_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _17_ (
    .A(_02_),
    .B(_03_),
    .Y(next_count[1])
  );
  sky130_fd_sc_hd__a21oi_1 _18_ (
    .A1(counter[1]),
    .A2(counter[0]),
    .B1(counter[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__and3_1 _19_ (
    .A(counter[1]),
    .B(counter[0]),
    .C(counter[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__nor3_1 _20_ (
    .A(_02_),
    .B(_04_),
    .C(_05_),
    .Y(next_count[2])
  );
  sky130_fd_sc_hd__and4_1 _21_ (
    .A(counter[1]),
    .B(counter[0]),
    .C(counter[3]),
    .D(counter[2]),
    .X(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _22_ (
    .A(counter[3]),
    .B(_05_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nor3_1 _23_ (
    .A(_02_),
    .B(_06_),
    .C(_07_),
    .Y(next_count[3])
  );
  sky130_fd_sc_hd__nor2_1 _24_ (
    .A(counter[4]),
    .B(_06_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _25_ (
    .A(counter[5]),
    .B(counter[4]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__a2111oi_0 _26_ (
    .A1(counter[4]),
    .A2(_06_),
    .B1(_08_),
    .C1(_09_),
    .D1(_02_),
    .Y(next_count[4])
  );
  sky130_fd_sc_hd__a21oi_1 _27_ (
    .A1(counter[4]),
    .A2(_06_),
    .B1(counter[5]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__and3_1 _28_ (
    .A(counter[5]),
    .B(counter[4]),
    .C(_06_),
    .X(_11_)
  );
  sky130_fd_sc_hd__nor3_1 _29_ (
    .A(_02_),
    .B(_10_),
    .C(_11_),
    .Y(next_count[5])
  );
  sky130_fd_sc_hd__and4b_1 _30_ (
    .A_N(edge_2),
    .B(edge_1),
    .C(accept),
    .D(_01_),
    .X(posout)
  );
  sky130_fd_sc_hd__a31oi_1 _31_ (
    .A1(_01_),
    .A2(_06_),
    .A3(_09_),
    .B1(accept),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _32_ (
    .A(posout),
    .B(_12_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__dfrtp_1 _33_ (
    .CLK(clk),
    .D(next_count[0]),
    .Q(counter[0]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clk),
    .D(next_count[1]),
    .Q(counter[1]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(clk),
    .D(next_count[2]),
    .Q(counter[2]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(clk),
    .D(next_count[3]),
    .Q(counter[3]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(clk),
    .D(next_count[4]),
    .Q(counter[4]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(clk),
    .D(next_count[5]),
    .Q(counter[5]),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _39_ (
    .CLK(clk),
    .D(sync_out),
    .Q(edge_1),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _40_ (
    .CLK(clk),
    .D(edge_1),
    .Q(edge_2),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _41_ (
    .CLK(clk),
    .D(button),
    .Q(sync_out),
    .RESET_B(n_rst)
  );
  sky130_fd_sc_hd__dfstp_2 _42_ (
    .CLK(clk),
    .D(_00_),
    .Q(accept),
    .SET_B(n_rst)
  );
endmodule
